<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQXSgOuQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQXSgOuQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQXSgOuQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQXSgOuQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQXSgOuQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'QXSgOuQ',
    'container.build_id' => '83a57c1c',
    'container.build_time' => 1664747841,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQXSgOuQ');
