name: CI

on:
  push:
    branches:
    - andrea

jobs:
  firebase-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '16.x'
    - run: npm install with --force
    - run: npm run build
    - uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.ANDREA_FIREBASE_TOKEN }}
